spring.application.name=IT3030_PAF_Assignment_2026_WD_320_4.2
spring.datasource.url=jdbc:sqlserver://localhost;instanceName=MSSQLLocalDB;databaseName=smart_campus;trustServerCertificate=true;integratedSecurity=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true